# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- quick-start

variables:
- group: Discourse Secrets

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    cd ./custom_deploy
    npm install
  displayName: 'Install dependencies'

- script: |
    cd ./custom_deploy
    node ./prepare-config.js --env.smtp.password=$(sendgridApiKey) --env.hostname=stingy
  displayName: 'Prepare app.yml for discourse'
